### PR TITLE
notation fix in groth-16 algo

### PR DESCRIPTION
**Pull request by TakeASwing-420**

### CODE REVIEW

**Comment by jeffreyscholz** [comment]
delta isn't squared, and it isn't possible to square it, as it is an elliptic curve point. What's the issue here?

**Comment by TakeASwing-420** [comment]
But while proving I think you took it as a scalar...can you re-check and confirm it?

**Comment by TakeASwing-420** [comment]
> delta isn't squared, and it isn't possible to square it, as it is an elliptic curve point. What's the issue here?

@jeffreyscholz , I checked that you have actually proved the equation without using the ecc pairing (simple algebra xD)...
>To derive the final verification formula, let's temporarily ignore that we don't know the discrete logs of the Greek letter terms and compute the left-hand-side of the verification equation $AB$:
$$(\alpha + \sum_{i=1}^m a_i u_i(x) + r\delta) \cdot (\beta + \sum_{i=1}^m a_i v_i(x) + s\delta)$$

**Comment by TakeASwing-420** [comment]
@RareSkills what about this one? should I close this PR?

**Pull request closed without merging**
